### ISSUE TITLE
fedora pdc - wrong url in API list

### ISSUE THREAD

**Issue by matysek** [product-definition-center/product-definition-center#352] opened 2016-05-03 15:25 UTC
Hello,

today I was looking at https://pdc.fedoraproject.org/rest_api/v1/ and found out that there are wrong urls to API endpoints containing `localhost` like this:

```
"arches": "http://localhost:10045/rest_api/v1/arches/",
"auth/current-user": "http://localhost:10045/rest_api/v1/auth/current-user/",
"auth/groups": "http://localhost:10045/rest_api/v1/auth/groups/",
```

Not sure if this issue should be reported here or not.

**Comment by bliuredhat** [comment] 2016-05-04 02:05
@matysek, the urls of API is wrong, which should start with "https://pdc.fedoraproject.org/rest_api/v1/ ",  such as: 
"arches": "https://pdc.fedoraproject.org/rest_api/v1/arches/".
But I am not sure the reason why it happened like this.

**Comment by lubomir** [comment] 2016-05-04 06:11
See #270. This is caused by having PDC behind reverse proxy.

**Comment by ralphbean** [comment] 2016-05-13 18:36
@lubomir figured it out.  This should be fixed now.

**Comment by matysek** [comment] 2016-05-13 21:12
When looking at https://pdc.fedoraproject.org/rest_api/v1/ the url is really fixed.

Well done guys.

**Closed** 2016-05-18 11:24 UTC
