### ISSUE TITLE
details about release status

### ISSUE THREAD

**Issue by keszybz** [product-definition-center/product-definition-center#294] opened 2016-03-03 22:23 UTC
Current information about releases does not provide enough information to distinguish released releases from future and EOL releases.

In the `https://pdc.fedoraproject.org/rest_api/v1/releases/*/` there could be new fields:
- status (one of "development", "released", "eol")
- release_date
- eol_date

The dates would be tentative until the event happens, and could be change over time, and should be set to the real date when the event happens.

This could be used in `dnf-plugin-system-upgrade` and LiveUsb Creator and similar. LUC currently gets the data from https://dl.fedoraproject.org/pub/fedora/linux/releases/ but it's rather slow (has to fetch and parse a lot of small files) and seems brittle.

@lmacken ?

**Comment by sochotnicky** [comment] 2016-03-04 07:37
The way we generally went about adding things is to add a new resource (i.e. something like "release-schedules" or similar).

Though at least partially - we do support the EOL use case by marking release as "active": "False". Distinguishing devel from releases is not there though...

**Comment by keszybz** [comment] 2016-03-04 13:02
Normally the whole reason for using an extensible format like XML or json is to be able to freely add new fields ;) I think there'd be a 1:1 mapping between a "release" and "release-schedule" so there isn't much reason to split them. But of course either option would work.

I don't think that the `active` field is useful: in the listings I see EOF releases are not shown (on https://pdc.fedoraproject.org/rest_api/v1/releases/), so active==True for all the ones that are present.

**Comment by AdamWill** [comment] 2017-08-18 20:59
Now Fedora's pkgdb is being decommissioned, this is an urgent issue for Fedora. The pkgdb 'collections' API listed all releases and had 'under development', 'active', and 'eol' states - so future releases would have 'under development' state, currently-supported stable releases would have 'active' state, and EOL releases would have 'eol' state. I have a project (fedfind) which provides helper functions for discovering 'current' releases based on the pkgdb collections API, and now I'm going to need to switch it to use PDC instead, but this is currently just flat out not possible due to the insufficient detail. For now I've had to cut a fedfind release which just has the current 'correct' answers hard-coded.

I'll also note that the graphical distribution upgrade code for Fedora in gnome-software similarly relies on the pkgdb API to determine what releases are available for upgrade, and it will also need porting to PDC, but it will similarly have trouble until this is fixed, because it obviously needs to distinguish between 'under development' and 'stable' releases.

**Comment by AdamWill** [comment] 2017-08-18 21:01
@ralphbean @hughsie

**Comment by hughsie** [comment] 2017-08-20 07:57
The low-tech solution for this could just be "someone manually modifying the file every branch/release". If there is a new location or web-service serving a different format of metadata then I'll need a bit of time to write a plugin and backport it to all the upgradable releases. Also note I'm going to be on paternity leave the first half of October (and probably a sleep deprived moron for a few weeks after that) so if you want sane engineering from me then it's going to need to be in the next few weeks.

**Comment by stickster** [comment] 2017-09-12 19:50
Every manual process is another thing to go wrong that needs human babysitting. We have plenty of those for releases already. ;-) AFAICT, PDC is the right place to support this since it's supposed to be the one true source of release information.

**Comment by ralphbean** [comment] 2017-09-19 18:50
Side note - I think if we do this a certain way, we'll get #459 for free.

**Comment by stickster** [comment] 2017-09-19 18:54
Note also #459 could be fixed in the same fell swoop, probably.

**Comment by ralphbean** [comment] 2017-09-19 18:56
One [swell foop!](https://wiki.gnome.org/Apps/Swell%20Foop)

**Comment by abompard** [comment] 2017-09-20 13:58
Hey folks! I'd like to help with that and write the patch.
Here's what I propose from my understanding of the issue and of the codebase:
- replace the `active` model field in `pdc.release.models.Release` by two fields, a `release_date` field and an `eol_date` field.
- add a `status` class property that would return `development` when `today() < release_date`, `eol` when `today() >= eol_date`, and `released` in between.
- export those fields in the serializer for the API
- for reverse compatibility, add an `active` class property that would return `status == "released"`

Then the information would be in the database and humans could update the release / EOL dates as they change, or import them from and external source with a simple script if necessary.

The data migration would be a bit tricky since I don't know the actual dates, but I could either look them up and hardcode them at the time of commit/push, or insert a dummy old eol_date for release that currently have `active` set to `False`.

What do you think of this plan? Am I missing something? Would you be interested in that code (provided it meets your coding standards of course)?

**Comment by lubomir** [comment] 2017-09-25 08:08
The proposed solution fairly good. The only issue is changing meaning of the existing `active` flag. That would break [the stability promise](http://product-definition-center.github.io/product-definition-center/using_api.html#pdc-api-stability-promise).

I would recommend adding this feature as a separate resource where the schedules would be linked by a release ID. It could be marked as experimental and then iterated on until it works as expected.

**Comment by abompard** [comment] 2017-10-04 09:44
I'm trying to design a fix that would solve #459 at the same time, but I'm not sure that the release status information could actually be shared. Say I have the following SLAs:
- bug_fixes
- security_fixes
- stable_api
- rawhide

If I only add default SLA dates for Releases, then I can't tell when it is actually released, because : 
- there is no SLA for "development" that would end on release date
- if I consider a Release to be "released" if it has at least one current SLA, then Rawhide is always "released", and the Gnome Software upgrade detection code won't like that.

If I only add a release "schedule" that links a Release to a status (`development`, `released` or `eol`) and a date, then it's not sufficient to derive default SLA dates for Releases because some release have different dates for the different SLAs.

I see two ways out:
- add both piecies of information : default SLAs and schedules for Releases
- add only default SLAs for Releases but also add a new "development" SLA that would be set to end on release date. I could have a dynamic property on that model that would tell which of the SLA are "current" for a Release, or none (empty list) if all SLA dates are in the past. I define "current" as "the SLA(s) that will expire next, but not those after that date". Since there can be SLAs expiring on the same date, I have to use a list here.

Am I missing something? Do you think it's OK to add this new `development` SLA? Do you forsee any side-effects with the rest of the resources using the SLAs? (ComponentBranches) I think it should be OK technically, but I may not see the whole use case and how it's used outside of Fedora.

@ralphbean, did you have something else in mind when you said that we could solve both issues at the same time?

**Comment by abompard** [comment] 2017-10-06 14:32
OK, here's my attempt at solving both issues. The pull requests adds a new endpoint (and a new app) that links releases to SLAs. If a "current" release is defined as, for example, being under the `bug_fixes` SLA (which makes sense I think), then all the current releases can be retrieved using an API request of the form:
```
/rest_api/v1/release-schedules/?sla=bug_fixes&active=1&fields=release"
```
Prereleases could then be defined as either having a `development` SLA that expires on release day, or having no SLA at all.

@AdamWill, do you think it could solve the issue here?

Since it links Releases to SLAs, it obviously solves #459.

**Comment by AdamWill** [comment] 2017-10-10 13:04
That seems like it'd work for what I need, yeah. It's a tad indirect, but I think it can work.

**Comment by AdamWill** [comment] 2017-11-13 23:09
ping?

**Comment by hughsie** [comment] 2017-11-14 10:06
So is this ready to use in gnome-software? Sorry, I'm a bit confused what to do.

**Comment by AdamWill** [comment] 2017-11-14 21:37
@hughsie https://github.com/product-definition-center/product-definition-center/pull/482#issuecomment-338877764 seems to be the current state. The old pkgdb 'collections' end point has been updated manually for the F27 release, so its data should be correct.

**Comment by stickster** [comment] 2018-01-15 16:20
Has anyone upstream reviewed this PR? It would be very helpful if we could get this considered soon and not miss the F28 boat.

**Comment by ralphbean** [comment] 2018-01-15 19:28
@stickster, FYI - I just cut a 1.9.0 pre-release rpm and upgraded it in our Fedora instance.

Once this is reviewed by the PDC dev team, ping me and I can fast-track another pre-release for us (using the same methods, for consistency).

**Closed** 2018-02-27 06:56 UTC

**Comment by pypingou** [comment] 2018-02-27 10:36
@ralphbean looks like @abompard 's PR has been merged :)

**Comment by ralphbean** [comment] 2018-02-27 21:17
I am needed! :fire_engine: :helicopter: :rocket: :guitar:

**Comment by ralphbean** [comment] 2018-02-27 21:31
Building:  https://koji.fedoraproject.org/koji/taskinfo?taskID=25352415

**Comment by AdamWill** [comment] 2018-02-27 21:33
you know, @ralphbean , that's *exactly* how I picture your daily routine...

**Comment by ralphbean** [comment] 2018-02-27 21:44
Ran into deployment issues in staging, unrelated to PDC:  https://pagure.io/fedora-infrastructure/issue/6753

**Comment by ralphbean** [comment] 2018-02-28 15:07
OK, staging updated with `playbooks/manual/upgrade/pdc.yml  -l pdc-web-stg`.

Please test at https://pdc.stg.fedoraproject.org/rest_api/v1/

Once confirmed, let me know.  We can move the build from `epel7-infra-stg` to `epel7-infra` and deploy to prod.

**Comment by ralphbean** [comment] 2018-03-01 09:13
Well, the new feature looks okay to me.

Will some other PDC functions in staging.

**Comment by pypingou** [comment] 2018-03-01 09:23
Is it expected that epel5-updates in https://pdc.stg.fedoraproject.org/rest_api/v1/releases/ is marked as active?

**Comment by ralphbean** [comment] 2018-03-01 09:26
Heh, it's [active in prod, too](https://pdc.fedoraproject.org/rest_api/v1/releases/epel-5-updates/).

**Comment by keszybz** [comment] 2018-03-01 09:57
How do I get the full list? `pdc_client -s fedora-stg -r /releases` only returns 20 items, but the header says that there are 28 releases.

**Comment by lubomir** [comment] 2018-03-01 10:14
@keszybz The simple client does not download multiple pages, you only get the first one. You can turn the paging off for your request:
`pdc_client -s fedora-stg -r releases -d '{"page_size": -1}'`

**Comment by lubomir** [comment] 2018-03-01 10:15
However the new feature in stage is this endpoint: https://pdc.stg.fedoraproject.org/rest_api/v1/release-schedules/
It's not tied to the `active` field on releases in any way.

**Comment by ralphbean** [comment] 2018-03-01 12:48
My testing of other endpoints (`/modules/` in particular) went fine.  The epel-5-updates data entry issue is unrelated to any code changes in this pre-release snapshot.

**Comment by ralphbean** [comment] 2018-03-02 00:10
OK, we're all updated now.

```
$ sudo -i ansible pdc-web\* -a "rpm -qa python-pdc"

pdc-web01.phx2.fedoraproject.org | SUCCESS | rc=0 >>
python-pdc-1.9.0-1.git.49.ga39a1b1.el7.noarch

pdc-web01.stg.phx2.fedoraproject.org | SUCCESS | rc=0 >>
python-pdc-1.9.0-1.git.49.ga39a1b1.el7.noarch

pdc-web02.phx2.fedoraproject.org | SUCCESS | rc=0 >>
python-pdc-1.9.0-1.git.49.ga39a1b1.el7.noarch
```

**Comment by AdamWill** [comment] 2018-03-06 01:24
Thanks a lot, folks.

**Comment by AdamWill** [comment] 2018-03-06 01:27
Who needs to do something to *populate* this endpoint? Both prod and stg seem to return no data for it at all, unless I'm missing something.

**Comment by ralphbean** [comment] 2018-03-06 15:01
No, you're right @AdamWill.

Who was updating the old pkgdb json blob?  That same kind of information could be shoved into PDC now (and the json blob could be convert to in turn read from PDC).

Maybe @abompard can follow up on the data, but I bet he's neck deep in hubs work.

**Comment by pypingou** [comment] 2018-03-06 15:42
I have been updating pkgdb manually and branch and release time via it's UI (and sometime Tyll to turn off the "allow retire" checkbox). rel-eng and infra could basically edit the content there.

**Comment by stickster** [comment] 2018-03-06 20:08
Whoever it is, let's make sure to get it in SOPs 👌

**Comment by AdamWill** [comment] 2018-03-07 21:04
@mohanboddu @ausil @kellinm looks like this needs to go into [releng SOPs](https://pagure.io/releng) - presumably this endpoint should be updated at mass branching (add new release) and EOL (change release to EOL status). And we obviously need a one-off action to create and populate it.

@stickster I'd think long-term we should drop the pkgdb JSON blob entirely, but yeah, as a transition thing, it could be automatically updated from this PDC endpoint somehow, I guess. I was planning to change all the things I have that use it to use PDC instead, as soon as PDC actually had the capability and the data.

**Comment by AdamWill** [comment] 2018-03-15 18:31
the endpoint also needs updating at release time, to move the release from the 'development' SLA to the 'bug-fixes' SLA, AIUI...
